version: "3"
services:
  webapp:
    container_name: bakehub
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    restart: always
    depends_on:
      - redis
      - rabbitmq
      - mysql
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./data/mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - .docker/rabbitmq/data/log:/data/log
      - .docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - .docker/rabbitmq/data/mnesia:/data/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}