springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  override-with-generic-response: false
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true