spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: user
    password: 1234

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  override-with-generic-response: false
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true